# Generated by Django 3.0.3 on 2020-07-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
